api:
    resource: '.'
    type: 'api_platform'

app:
    resource: '@AppBundle/Controller/'
    type: 'annotation'

ResqueBundle:
    resource: "@ResqueBundle/Resources/config/routing.xml"
    prefix:   /resque

_monitor:
    resource: "@LiipMonitorBundle/Resources/config/routing.xml"
    prefix: /monitor/health
