# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.orion.update:
      alias: guzzle.client.orion_update

    app.orion.query:
      alias: guzzle.client.orion_query

    app.odaa.fetch:
      alias: guzzle.client.odaa

    app.feed_reader_factory:
      class: AppBundle\Service\FeedReaderFactory
      arguments: ["@app.odaa.fetch", "@app.orion.update"]
